### ISSUE TITLE
`cargo compete new` fails if the contest name contains '-'.

### ISSUE THREAD

**Issue by tyu-ru** [qryxip/cargo-compete#115]
[nikkei2019-2-qual](https://atcoder.jp/contests/nikkei2019-2-qual)や[dwacon6th-prelims](https://atcoder.jp/contests/dwacon6th-prelims)などのコンテスト名にハイフンが入る場合処理の途中でエスケープされてしまい、`cargo compete new`が失敗するようです

```bash
$ cargo compete -V
cargo-compete 0.7.1
$ cargo compete new nikkei2019-2-qual
error: Invalid character `%` in crate name: `nikkei2019%2D2%2Dqual`
error: `*********/.rustup/toolchains/1.42.0-x86_64-unknown-linux-gnu/bin/cargo new -q --vcs none --name 'nikkei2019%2D2%2Dqual' '*************/./nikkei2019%2D2%2Dqual'` didn't exit successfully: exit code: 101
```
(一部パスを伏せました)

v0.7.0からこの問題が発生してるようです(v0.7.1, v0.7.0で発生を確認しましたが、v0.6.5では発生しませんでした)

**Comment by qryxip** [comment]
報告ありがとうございます．これはちょっとひどい...

**Comment by qryxip** [comment]
[v0.8.0をリリースしました](https://github.com/qryxip/cargo-compete/releases/tag/v0.8.0)．
