### ISSUE TITLE
compete test process becomes Zombie when the program has infinite loop

### ISSUE THREAD

**Issue by hayashikun** [qryxip/cargo-compete#135]
- 環境: macOS Big Sur
- cargo-compete version 0.8.4

プログラムに無限ループ箇所がある状態で `cargo compete test abcxxx-x` としてテストすると `Timelimit Exceeded` になりますが、
その際に親プロセスだけがkillされてゾンビ子プロセスが残ります

![Screen Shot 2021-02-22 at 14 49 43](https://user-images.githubusercontent.com/5352478/108667841-5970d400-751d-11eb-97ad-5800a9091f9a.png)

軽くコードを見たところ、judge自体は `snowchains` でやっているようなのでそちらの問題なのかもしれませんが。
ひとまずこちらにIssueを投げます

よろしくお願いします🙇‍♂️

**Comment by qryxip** [comment]
原因がわかりました。`tokio::process::Child::kill`に`.await`を付け忘れていました。報告ありがとうございます。

**Comment by qryxip** [comment]
[v0.8.5をリリースしました](https://github.com/qryxip/cargo-compete/releases/tag/v0.8.5)。
