### ISSUE TITLE
Add mention for --exclude-atcoder-crates for submit.transpile in README.md

### ISSUE THREAD

**Issue by aobatact** [qryxip/cargo-compete#155]
cargo equip を使ってatcoderに提出する際、compete.toml の submit.transpile のコメントアウトを外すだけだとエラーが起きます。
エラーメッセージで"--exclude-atcoder-crates"、を足せばいいと出るので修正自体は楽なのですが、README.md やREADME-ja.mdに記載があると親切かなと思いましたが、いかがでしょうか。

**Comment by qryxip** [comment]
手元で自分が使う`compete.toml`だけ変更して`cargo compete init`のテンプレートを変更するのを忘れていました。
