### ISSUE TITLE
テストケースを取得できないコンテストがある

### ISSUE THREAD

**Issue by ryo-n** [qryxip/cargo-compete#42]
abc003のテストケースを取得しようとしたのですが下記エラーが発生しテストケースを取得できませんでした。

##  再現方法
```
$ cargo compete new abc003
error: Could not extract the timelimit
```

## 環境

macOS 10.13.6

```
$ cargo compete --version
cargo-compete 0.4.1
```
```
$ rustc --version
rustc 1.42.0 (b8cedc004 2020-03-09)
```

**Comment by qryxip** [comment]
原因はわかりました。 cargo-competeでは[印刷用問題文]を`#main-container > div.row > div.col-sm-12`で区切っているのですが、ABC003だとAの中にB, C, Dが入りこんでいるようです。 個別の問題文から自動で合体しているんじゃなかったのか...

![Screenshot](https://user-images.githubusercontent.com/14125495/90427051-f67d2b00-e0fc-11ea-90d4-4f4e11f5fe32.png)

**Comment by ryo-n** [comment]
似た問題だと思うのですがabc007-abc010ではサンプル取得で失敗してそうです。
```
$ cargo compete new abc007
error: Could not extract the sample cases
```

**Comment by qryxip** [comment]
とりあえずこれでABC003もABC007-ABC010もいけるっぽい...

```diff
     fn extract_samples(&self) -> anyhow::Result<IndexMap<String, TestSuite>> {
         return self
             .select(static_selector!(
-                "#main-container > div.row > div[class=\"col-sm-12\"]",
+                "#main-container > div.row div[class=\"col-sm-12\"]",
             ))
             .map(|div| {
                 let display_name = div
-                    .select(static_selector!("span"))
+                    .select(static_selector!(":scope > span"))
                     .flat_map(|r| r.text())
                     .next()
                     .and_then(|s| static_regex!(r"[A-Z0-9]+ - (.+)").captures(s))
                     .map(|caps| caps[1].to_owned())
                     .with_context(|| "Could not extract the display name")?;

                 let timelimit = div
-                    .select(static_selector!("p"))
+                    .select(static_selector!(":scope > p"))
                     .flat_map(|r| r.text())
                     .flat_map(parse_timelimit)
                     .exactly_one()
                     .ok()
                     .with_context(|| "Could not extract the timelimit")?;

                 // In `tasks_print`, there are multiple `#task-statement`s.
                 let samples = div
-                    .select(static_selector!("div[id=\"task-statement\"]"))
+                    .select(static_selector!(":scope > div[id=\"task-statement\"]"))
                     .exactly_one()
                     .ok()
                     .and_then(extract_samples)
                     .with_context(|| "Could not extract the sample cases")?;

                 let test_suite = if timelimit == Duration::new(0, 0) {
                     TestSuite::Unsubmittable
                 } else if let Samples::Batch(r#match, samples) = samples {
                     TestSuite::Batch(BatchTestSuite {
```

**Comment by qryxip** [comment]
v0.4.3をリリースしました。ARC/ABCすべてをチェックしたわけではないし多分まだあるのでこのissueはこのままで。

**Comment by ryo-n** [comment]
ありがとうございます。
abc003もabc007-010でサンプル取得できることを確認しました。

アプデ後のバージョン(v0.4.3)でabc175, arc103, agc047まで確認したところ下記コンテストでサンプル取得に失敗しました。

* abc019
  * [abc019-d](https://atcoder.jp/contests/abc019/tasks/abc019_4)がインタラクティブ問題なためサンプルが無いのが原因かと思います。
* arc019
  * [arc019-d](https://atcoder.jp/contests/arc019/tasks/arc019_4) が入力例が存在しないためかと思います。
* arc021
  * [arc021-d](https://atcoder.jp/contests/arc021/tasks/arc021_4) 入力が特殊だからかと思います
* agc028
  * [f2](https://atcoder.jp/contests/agc028/tasks/agc028_f2)が存在するから?
* agc042
  * これは公開されていないだけなので取得できない状態で正しいです。
* agc044
  * [agc044-d](https://atcoder.jp/contests/agc044/tasks/agc044_d)がインタラクティブ問題なためサンプルが無いのが原因かと思います。

**Comment by qryxip** [comment]
なるほど...ありがとうございます。AGC028とAGC044は対応が必要ですね。

- AGC028
    [印刷用ページ](https://atcoder.jp/contests/agc028/tasks_print)に`div[class="col-sm-12"]`はちゃんと7つあるように見えるので謎。
- AGC044
    インタラクティブ問題は「インタラクティブ」/"Interactive"が入っているかで判定していたのですが「対話式」って... 下手するとこれが最新のインタラクティブ問題だし恒久的に注釈テンプレートが変わっている可能性がありますね。

サンプルが読めない場合にwarningだけ出してスキップというのは、した方が良いですねこの感じだと。いつか本番で踏みそう。

**Comment by qryxip** [comment]
v0.4.5をリリースしました。サンプルが読めない場合にwarningだけ出して続行するようになりました。
