### ISSUE TITLE
v0.5 以降、Codeforces のコンテストで cargo compete new がエラーとなる

### ISSUE THREAD

**Issue by Loptall** [qryxip/cargo-compete#62]
```
error: Package names starting with a digit cannot be used as a crate name
error: `/Users/yuta/.rustup/toolchains/1.42.0-x86_64-apple-darwin/bin/cargo new -q --vcs none --name 1397 1397` didn't exit successfully: exit code: 101
```
コンテスト名が数字で始まるのが原因のようです

**Comment by qryxip** [comment]
報告ありがとうございます。1.42.0までなら`cargo new`をなんとかすればいいですが、1.43以降だと何らかのprefixを付けないと駄目になりますね。

https://github.com/rust-lang/cargo/pull/7959

というかv0.1.0から今に至るまでyukicoder全く動いてないことになりますね。使ってないしテストも書いてないから気づきませんでした。

**Comment by qryxip** [comment]
v0.6.0をリリースしました。
