### ISSUE TITLE
Notarization check on macOS makes the testcase fails due to Timelimit on the first run

### ISSUE THREAD

**Issue by itchyny** [qryxip/cargo-compete#65]
It seems that when `cargo compete test` for the first time after editing the source code, it's likely to exceed the time limit due to the building duration. Can you exclude building time from judging the timelimit? Great tool for Codeforces anyway, thanks.

**Comment by qryxip** [comment]
That is a... little strange. Timelimits are considered not to included building time.

https://github.com/qryxip/cargo-compete/blob/master/src/testing.rs#L66-L96

I suspect that we have something deep-seated problem. For example, wrong executables may be executed "for the first time" in your environment.

**Comment by itchyny** [comment]
Oh, sorry, ok. This is caused not by building time, but the notarization process on macOS. Newly created executable has overhead on its first run, causing delay more than a second and results into `Timelimit Exceeded`.

**Comment by qryxip** [comment]
> causing delay more than a second

I didn't know notarization takes so long. (I don't have any macOS PC)

As a workaround, you can disable timelimits by removing `timelimit`s from each `{{ manifest_dir }}/testcases/{{ problem_index }}.yml` with `sed` or something.

```diff
 ---
 type: Batch
-timelimit: 1s
 match: Lines

 cases:
   - name: example1
     in: |
       6 6 4
     out: |
       4

 extend: []
```

**Comment by itchyny** [comment]
Okay, thanks. Maybe there's a workaround by invoking the executable once before spawning each test cases. For record, this is the screenshot how it works currently.
![](https://user-images.githubusercontent.com/375258/92990244-c2d3cc00-f515-11ea-9e83-f798e734d0d8.gif)

By the way, can I remove the timelimit by default on `cargo compete new` command?
